# Encode the columns in the datasets

In [53]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,MultiLabelBinarizer
lable = LabelEncoder()
multi_label = MultiLabelBinarizer()

In [54]:
df = pd.read_csv(r'Datasets/india_housing_prices_with_target_columns.csv')
df.head()

         State      City  ... Amenities_Count Good_Investment
0   Tamil Nadu   Chennai  ...               5               0
1  Maharashtra      Pune  ...               5               0
2       Punjab  Ludhiana  ...               4               1
3    Rajasthan   Jodhpur  ...               5               0
4    Rajasthan    Jaipur  ...               5               1

[5 rows x 26 columns]

### One Hot Encoding the City column

In [55]:
df['City'] = df['City'].str.replace(' ', '_')
df = pd.get_dummies(df,columns=['City'],prefix='City',dtype=int)

df.head()

         State      Locality  ... City_Vishakhapatnam  City_Warangal
0   Tamil Nadu   Locality_84  ...                   0              0
1  Maharashtra  Locality_490  ...                   0              0
2       Punjab  Locality_167  ...                   0              0
3    Rajasthan  Locality_393  ...                   0              0
4    Rajasthan  Locality_466  ...                   0              0

[5 rows x 67 columns]

### One Hot Encoding the Property Type column

In [56]:
df['Property_Type'] = df['Property_Type'].str.replace(' ', '_')
df = pd.get_dummies(df,columns=['Property_Type'],prefix='Property_Type',dtype=int)
df.head()

         State  ... Property_Type_Villa
0   Tamil Nadu  ...                   0
1  Maharashtra  ...                   0
2       Punjab  ...                   0
3    Rajasthan  ...                   0
4    Rajasthan  ...                   1

[5 rows x 69 columns]

### One Hot Encoding the Facing column

In [57]:
df = pd.get_dummies(df,columns=['Facing'],prefix='Facing',dtype=int)
df.head()

         State      Locality  BHK  ...  Facing_North  Facing_South  Facing_West
0   Tamil Nadu   Locality_84    1  ...             0             0            1
1  Maharashtra  Locality_490    3  ...             1             0            0
2       Punjab  Locality_167    2  ...             0             1            0
3    Rajasthan  Locality_393    2  ...             1             0            0
4    Rajasthan  Locality_466    4  ...             0             0            0

[5 rows x 72 columns]

### One Hot Encoding the Furnished Status column

In [58]:
df['Furnished_Status'] = df['Furnished_Status'].str.replace('-', ' ').str.title().str.replace(' ', '_')
df = pd.get_dummies(df,columns=['Furnished_Status'],prefix='Furnished_Status',dtype=int)
df.head()

         State  ... Furnished_Status_Unfurnished
0   Tamil Nadu  ...                            0
1  Maharashtra  ...                            1
2       Punjab  ...                            0
3    Rajasthan  ...                            0
4    Rajasthan  ...                            0

[5 rows x 74 columns]

### One Hot Encoding the Owner Type column

In [59]:
df = pd.get_dummies(df,columns=['Owner_Type'],prefix='Owner_Type',dtype=int)
df.head()

         State      Locality  ...  Owner_Type_Builder  Owner_Type_Owner
0   Tamil Nadu   Locality_84  ...                   0                 1
1  Maharashtra  Locality_490  ...                   1                 0
2       Punjab  Locality_167  ...                   0                 0
3    Rajasthan  Locality_393  ...                   1                 0
4    Rajasthan  Locality_466  ...                   1                 0

[5 rows x 76 columns]

### Label Encoding the Availability Status column

In [60]:
df['Availability_Status'] = lable.fit_transform(df['Availability_Status'])
class_mapping = dict(zip(lable.classes_, range(len(lable.classes_))))
print("Class Mapping:", class_mapping)

Class Mapping: {'Ready_to_Move': 0, 'Under_Construction': 1}

### Label Encoding the Parking Space column

In [61]:
df['Parking_Space'] = lable.fit_transform(df['Parking_Space'])
class_mapping = dict(zip(lable.classes_, range(len(lable.classes_))))
print("Class Mapping:", class_mapping)

Class Mapping: {'No': 0, 'Yes': 1}

### Label Encoding the Security column

In [62]:
df['Security'] = lable.fit_transform(df['Security'])
class_mapping = dict(zip(lable.classes_, range(len(lable.classes_))))
print("Class Mapping:", class_mapping)

Class Mapping: {'No': 0, 'Yes': 1}

### Ordinal Encoding the Public Transport Accessibility column

In [63]:
unique_condition = ['Low','Medium','High']
conditions_mapping = {k:i for i,k in enumerate(unique_condition)}
df['Public_Transport_Accessibility'] = df['Public_Transport_Accessibility'].map(conditions_mapping)

In [64]:
# Save the encoded dataframe to file
df.to_csv('Datasets/india_housing_prices_with_target_columns_encoded.csv',index=False)