# Encode the columns in the datasets

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,MultiLabelBinarizer

In [6]:
df = pd.read_csv(r'Datasets/india_housing_prices_with_target_columns.csv')
df.head()

         State      City  ... Amenities_Count Good_Investment
0   Tamil Nadu   Chennai  ...               5               0
1  Maharashtra      Pune  ...               5               0
2       Punjab  Ludhiana  ...               4               1
3    Rajasthan   Jodhpur  ...               5               0
4    Rajasthan    Jaipur  ...               5               1

[5 rows x 26 columns]

### One Hot Encoding the City column

In [7]:
df = pd.get_dummies(df,columns=['City'],prefix='city',dtype=int)
df.head()

         State      Locality  ... city_Vishakhapatnam  city_Warangal
0   Tamil Nadu   Locality_84  ...                   0              0
1  Maharashtra  Locality_490  ...                   0              0
2       Punjab  Locality_167  ...                   0              0
3    Rajasthan  Locality_393  ...                   0              0
4    Rajasthan  Locality_466  ...                   0              0

[5 rows x 67 columns]

### One Hot Encoding the Property Type column

In [8]:
df = pd.get_dummies(df,columns=['Property_Type'],prefix='property_type',dtype=int)
df.head()

         State  ... property_type_Villa
0   Tamil Nadu  ...                   0
1  Maharashtra  ...                   0
2       Punjab  ...                   0
3    Rajasthan  ...                   0
4    Rajasthan  ...                   1

[5 rows x 69 columns]